title: Theresia Evelyn
logo: /assets/img/headshot_circle.png
description: Evelyn is a Bachelor of Public Health specializing in Biostatistics. A Junior Data Analyst. She is also writing for various occasions in between.
show_downloads: true
theme: jekyll-theme-minimal
