title: Theresia Evelyn
logo: "/images/logo.png?raw=true"
description: >
Evelyn is a Junior Data Analyst with Public Health degree, specializing in Biostatistics.
show_downloads: true
theme: jekyll-theme-minimal

<br><br>

<a href="https://www.linkedin.com/in/example/"> Evelyn's LinkedIn Profile</a>

<br><br>
<a href="#" class="icon brands fa-twitter"><span class="label">Twitter</span></a>
<a href="#" class="icon brands fa-facebook-f"><span class="label">Facebook</span></a>
<a href="#" class="icon brands fa-instagram"><span class="label">Instagram</span></a>
<a href="#" class="icon brands fa-github"><span class="label">Github</span></a>
<a href="#" class="icon brands fa-dribbble"><span class="label">Dribbble</span></a>
<a href="#" class="icon brands fa-tumblr"><span class="label">Tumblr</span></a>
