title: Theresia Evelyn
logo: /assets/img/headshot_circle.png
description: Evelyn is a Junior Data Analyst with Public Health degree, specializing in Biostatistics.
show_downloads: true
theme: jekyll-theme-minimal
